In [1]:
import numpy as np

# 数据类型

|类型|解释|
|:-:|:-:|
|bool|布尔类型，1 个字节，值为 True 或 False。|
|int|整数类型，通常为 int64 或 int32 。|
|intc|与 C 里的 int 相同，通常为 int32 或 int64。|
|intp|用于索引，通常为 int32 或 int64。|
|int8|字节（从 -128 到 127）|
|int16|整数（从 -32768 到 32767）|
|int32|整数（从 -2147483648 到 2147483647）|
|int64|整数（从 -9223372036854775808 到 9223372036854775807）|
|uint8|无符号整数（从 0 到 255）|
|uint16|无符号整数（从 0 到 65535）|
|uint32|无符号整数（从 0 到 4294967295）|
|uint64|无符号整数（从 0 到 18446744073709551615）|
|float|float64 的简写。|
|float16|半精度浮点，5 位指数，10 位尾数|
|float32|单精度浮点，8 位指数，23 位尾数|
|float64|双精度浮点，11 位指数，52 位尾数|
|complex|complex128 的简写。|
|complex64|复数，由两个 32 位浮点表示。|
|complex128|复数，由两个 64 位浮点表示。|

# 数组生成  
ndarray 类具有六个参数，它们分别为：  
+ shape：数组的形状。  
+ dtype：数据类型。  
+ buffer：对象暴露缓冲区接口。  
+ offset：数组数据的偏移量。  
+ strides：数据步长。  
+ order：{'C'，'F'}，以行或列为主排列顺序。  
  
**numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)**  
  
object：列表、元组等。  
dtype：数据类型。如果未给出，则类型为被保存对象所需的最小类型。  
copy：布尔类型，默认 True，表示复制对象。  
order：顺序。  
subok：布尔类型，表示子类是否被传递。  
ndmin：生成的数组应具有的最小维数。

In [2]:
demo = np.array([[1, 2, 3], [4, 5, 6]])
demo, demo.shape, demo.dtype


(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3),
 dtype('int32'))

## 创建一系列均匀间隔的值  
设置起始，结束，间隔  
numpy.arange(start, stop, step, dtype=None)  
  
设置起始，结束，数量  
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)  
* start：序列的起始值。  
* stop：序列的结束值。  
* num：生成的样本数。默认值为50。  
* endpoint：布尔值，如果为真，则最后一个样本包含在序列内。  
* retstep：布尔值，如果为真，返回间距。  
* dtype：数组的类型。

In [3]:
np.arange(3, 7, 0.5, dtype='float32')

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5], dtype=float32)

In [4]:
np.linspace(0, 10, 10, endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 特殊数组生成  
**numpy.ones 用于快速创建数值全部为 1 的多维数组。其方法如下：**  
  
numpy.ones(shape, dtype=None, order='C')  
- shape：用于指定数组形状，例如（1， 2）或 3。  
- dtype：数据类型。  
- order：{'C'，'F'}，按行或列方式储存数组。  
  
**zeros 方法和上面的 ones 方法非常相似，不同的地方在于，这里全部填充为 0。zeros 方法和 ones 是一致的。**  
  
numpy.zeros(shape, dtype=None, order='C')

In [5]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**numpy.eye 用于创建一个二维数组，其特点是k 对角线上的值为 1，其余值全部为0。方法如下：**  
  
numpy.eye(N, M=None, k=0, dtype=<type 'float'>)  
- N：输出数组的行数。  
- M：输出数组的列数。  
- k：对角线索引：0（默认）是指主对角线，正值是指上对角线，负值是指下对角线。

In [7]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 从已知数据创建  
- frombuffer（buffer）：将缓冲区转换为 1 维数组。  
- fromfile（file，dtype，count，sep）：从文本或二进制文件中构建多维数组。  
- fromfunction（function，shape）：通过函数返回值来创建多维数组。  
- fromiter（iterable，dtype，count）：从可迭代对象创建 1 维数组。  
- fromstring（string，dtype，count，sep）：从字符串中创建 1 维数组。

In [8]:
np.fromfunction(lambda a, b: a + b, (5, 4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.],
       [4., 5., 6., 7.]])

## 数组属性

In [9]:
demo = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
demo

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 数组转置

In [10]:
demo.T, demo.transpose()

(array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]))

### 输出数组包含元素的数据类型

In [11]:
demo.dtype

dtype('int32')

### 输出数组包含元素的虚部

In [12]:
demo.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### 输出数组包含元素的实部

In [13]:
demo.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 输出数组中的总包含元素数

In [14]:
demo.size

9

### 输出数组的元素总字节数

In [15]:
demo.nbytes

36

### 输出数组维度

In [16]:
demo.ndim

2

### 输出数组形状

In [17]:
demo.shape

(3, 3)

### 遍历数组时，输出每个维度中步进的字节数组。

In [18]:
demo.strides

(12, 4)

# 数组基本操作  
## 重设形状

In [21]:
demo = np.arange(10)
demo, demo.reshape((2, 5))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

## 数组展开  
ravel 的目的是将任意形状的数组扁平化，变为 1 维数组。ravel 方法如下：  
numpy.ravel(a, order='C')  
  
其中，a 表示需要处理的数组。order 表示变换时的读取顺序，默认是按照行依次读取，当 order='F' 时，可以按列依次读取排序。

In [28]:
demo = np.arange(10).reshape(5, 2)
demo, np.ravel(demo, order='F')

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9]))

## 轴移动  
moveaxis 可以将数组的轴移动到新的位置。其方法如下：  
numpy.moveaxis(a, source, destination)  
  
+ a：数组。  
+ source：要移动的轴的原始位置。  
+ destination：要移动的轴的目标位置。

In [31]:
demo = np.ones((1, 2, 3))
demo, demo.shape, np.moveaxis(demo, 0, -1), np.moveaxis(demo, 0, -1).shape

(array([[[1., 1., 1.],
         [1., 1., 1.]]]),
 (1, 2, 3),
 array([[[1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.]]]),
 (2, 3, 1))

## 轴交换  
和 moveaxis 不同的是，swapaxes 可以用来交换数组的轴。其方法如下：  
numpy.swapaxes(a, axis1, axis2)  
  
+ a：数组。  
+ axis1：需要交换的轴 1 位置。  
+ axis2：需要与轴 1 交换位置的轴 1 位置。

In [33]:
demo = np.ones((1, 4, 3))
demo, demo.shape, np.swapaxes(demo, 0, 2), np.swapaxes(demo, 0, 2).shape

(array([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]),
 (1, 4, 3),
 array([[[1.],
         [1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.],
         [1.]]]),
 (3, 4, 1))