In [1]:
import numpy as np

# 数据类型

|类型|解释|
|:-:|:-:|
|bool|布尔类型，1 个字节，值为 True 或 False。|
|int|整数类型，通常为 int64 或 int32 。|
|intc|与 C 里的 int 相同，通常为 int32 或 int64。|
|intp|用于索引，通常为 int32 或 int64。|
|int8|字节（从 -128 到 127）|
|int16|整数（从 -32768 到 32767）|
|int32|整数（从 -2147483648 到 2147483647）|
|int64|整数（从 -9223372036854775808 到 9223372036854775807）|
|uint8|无符号整数（从 0 到 255）|
|uint16|无符号整数（从 0 到 65535）|
|uint32|无符号整数（从 0 到 4294967295）|
|uint64|无符号整数（从 0 到 18446744073709551615）|
|float|float64 的简写。|
|float16|半精度浮点，5 位指数，10 位尾数|
|float32|单精度浮点，8 位指数，23 位尾数|
|float64|双精度浮点，11 位指数，52 位尾数|
|complex|complex128 的简写。|
|complex64|复数，由两个 32 位浮点表示。|
|complex128|复数，由两个 64 位浮点表示。|

# 数组生成  
ndarray 类具有六个参数，它们分别为：  
+ shape：数组的形状。  
+ dtype：数据类型。  
+ buffer：对象暴露缓冲区接口。  
+ offset：数组数据的偏移量。  
+ strides：数据步长。  
+ order：{'C'，'F'}，以行或列为主排列顺序。  
  
**numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)**  
  
object：列表、元组等。  
dtype：数据类型。如果未给出，则类型为被保存对象所需的最小类型。  
copy：布尔类型，默认 True，表示复制对象。  
order：顺序。  
subok：布尔类型，表示子类是否被传递。  
ndmin：生成的数组应具有的最小维数。

In [2]:
demo = np.array([[1, 2, 3], [4, 5, 6]])
demo, demo.shape, demo.dtype


(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3),
 dtype('int32'))

## 创建一系列均匀间隔的值  
设置起始，结束，间隔  
numpy.arange(start, stop, step, dtype=None)  
  
设置起始，结束，数量  
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)  
* start：序列的起始值。  
* stop：序列的结束值。  
* num：生成的样本数。默认值为50。  
* endpoint：布尔值，如果为真，则最后一个样本包含在序列内。  
* retstep：布尔值，如果为真，返回间距。  
* dtype：数组的类型。

In [3]:
np.arange(3, 7, 0.5, dtype='float32')

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5], dtype=float32)

In [4]:
np.linspace(0, 10, 10, endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 特殊数组生成  
**numpy.ones 用于快速创建数值全部为 1 的多维数组。其方法如下：**  
  
numpy.ones(shape, dtype=None, order='C')  
- shape：用于指定数组形状，例如（1， 2）或 3。  
- dtype：数据类型。  
- order：{'C'，'F'}，按行或列方式储存数组。  
  
**zeros 方法和上面的 ones 方法非常相似，不同的地方在于，这里全部填充为 0。zeros 方法和 ones 是一致的。**  
  
numpy.zeros(shape, dtype=None, order='C')

In [5]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**numpy.eye 用于创建一个二维数组，其特点是k 对角线上的值为 1，其余值全部为0。方法如下：**  
  
numpy.eye(N, M=None, k=0, dtype=<type 'float'>)  
- N：输出数组的行数。  
- M：输出数组的列数。  
- k：对角线索引：0（默认）是指主对角线，正值是指上对角线，负值是指下对角线。

In [7]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 从已知数据创建  
- frombuffer（buffer）：将缓冲区转换为 1 维数组。  
- fromfile（file，dtype，count，sep）：从文本或二进制文件中构建多维数组。  
- fromfunction（function，shape）：通过函数返回值来创建多维数组。  
- fromiter（iterable，dtype，count）：从可迭代对象创建 1 维数组。  
- fromstring（string，dtype，count，sep）：从字符串中创建 1 维数组。

In [8]:
np.fromfunction(lambda a, b: a + b, (5, 4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.],
       [4., 5., 6., 7.]])

## 数组属性

In [9]:
demo = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
demo

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 数组转置

In [10]:
demo.T, demo.transpose()

(array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]))

### 输出数组包含元素的数据类型

In [11]:
demo.dtype

dtype('int32')

### 输出数组包含元素的虚部

In [12]:
demo.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### 输出数组包含元素的实部

In [13]:
demo.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 输出数组中的总包含元素数

In [14]:
demo.size

9

### 输出数组的元素总字节数

In [15]:
demo.nbytes

36

### 输出数组维度

In [16]:
demo.ndim

2

### 输出数组形状

In [17]:
demo.shape

(3, 3)

### 遍历数组时，输出每个维度中步进的字节数组。

In [18]:
demo.strides

(12, 4)

# 数组基本操作  
## 重设形状

In [19]:
demo = np.arange(10)
demo, demo.reshape((2, 5))

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

## 数组展开  
ravel 的目的是将任意形状的数组扁平化，变为 1 维数组。ravel 方法如下：  
numpy.ravel(a, order='C')  
  
其中，a 表示需要处理的数组。order 表示变换时的读取顺序，默认是按照行依次读取，当 order='F' 时，可以按列依次读取排序。

In [20]:
demo = np.arange(10).reshape(5, 2)
demo, np.ravel(demo, order='F')

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9]))

## 轴移动  
moveaxis 可以将数组的轴移动到新的位置。其方法如下：  
numpy.moveaxis(a, source, destination)  
  
+ a：数组。  
+ source：要移动的轴的原始位置。  
+ destination：要移动的轴的目标位置。

In [21]:
demo = np.ones((1, 2, 3))
demo, demo.shape, np.moveaxis(demo, 0, -1), np.moveaxis(demo, 0, -1).shape

(array([[[1., 1., 1.],
         [1., 1., 1.]]]),
 (1, 2, 3),
 array([[[1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.]]]),
 (2, 3, 1))

## 轴交换  
和 moveaxis 不同的是，swapaxes 可以用来交换数组的轴。其方法如下：  
numpy.swapaxes(a, axis1, axis2)  
  
+ a：数组。  
+ axis1：需要交换的轴 1 位置。  
+ axis2：需要与轴 1 交换位置的轴 1 位置。

In [22]:
demo = np.ones((1, 4, 3))
demo, demo.shape, np.swapaxes(demo, 0, 2), np.swapaxes(demo, 0, 2).shape

(array([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]),
 (1, 4, 3),
 array([[[1.],
         [1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.],
         [1.]]]),
 (3, 4, 1))

## 维度改变  
atleast_xd 支持将输入数据直接视为 x维。这里的 x 可以表示：1，2，3。方法分别为：  
numpy.atleast_1d()  
numpy.atleast_2d()  
numpy.atleast_3d()

In [23]:
np.atleast_1d([1, 2, 3]), np.atleast_2d([4, 5, 6]), np.atleast_3d([7, 8, 9])

(array([1, 2, 3]),
 array([[4, 5, 6]]),
 array([[[7],
         [8],
         [9]]]))

## 类型转换  
+ asarray(a，dtype，order)：将特定输入转换为数组。  
+ asanyarray(a，dtype，order)：将特定输入转换为 ndarray。  
+ asmatrix(data，dtype)：将特定输入转换为矩阵。  
+ asfarray(a，dtype)：将特定输入转换为 float 类型的数组。  
+ asarray_chkfinite(a，dtype，order)：将特定输入转换为数组，检查 NaN 或 infs。  
+ asscalar(a)：将大小为 1 的数组转换为标量。

In [24]:
demo = np.arange(4).reshape((2, 2))
demo, np.asmatrix(demo)

(array([[0, 1],
        [2, 3]]),
 matrix([[0, 1],
         [2, 3]]))

## 数组连接  
concatenate 可以将多个数组沿指定轴连接在一起。其方法为：  
numpy.concatenate((a1, a2, ...), axis=0)  
  
* (a1, a2, ...)：需要连接的数组。  
* axis：指定连接轴。

In [25]:
demo1 = np.array([[1, 2], [3, 4], [5, 6]])
demo2 = np.array([[7, 8], [9, 10]])
demo3 = np.array([[11, 12]])
np.concatenate((demo1, demo2, demo3), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

可以尝试沿着横轴连接。但要保证连接处的维数一致，所以这里用到了 .T 转置。

In [26]:
demo1 = np.array([[1, 2], [3, 4], [5, 6]])
demo2 = np.array([[7, 8, 9]])
np.concatenate((demo1, demo2.T), axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

## 数组堆叠  
* stack(arrays，axis)：沿着新轴连接数组的序列。  
* column_stack()：将 1 维数组作为列堆叠到 2 维数组中。  
* hstack()：按水平方向堆叠数组。  
* vstack()：按垂直方向堆叠数组。  
* dstack()：按深度方向堆叠数组。

In [27]:
demo1 = np.array([1, 2, 3])
demo2 = np.array([4, 5, 6])
np.stack((demo1, demo2)), np.stack((demo1, demo2), axis=-1)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

## 拆分  
* split(ary，indices_or_sections，axis)：将数组拆分为多个子数组。  
* dsplit(ary，indices_or_sections)：按深度方向将数组拆分成多个子数组。  
* hsplit(ary，indices_or_sections)：按水平方向将数组拆分成多个子数组。  
* vsplit(ary，indices_or_sections)：按垂直方向将数组拆分成多个子数组。

In [28]:
demo = np.arange(10)
np.split(demo, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

## 删除  
delete(arr，obj，axis)：沿特定轴删除数组中的子数组。

In [29]:
demo = np.arange(12).reshape(3, 4)
demo, np.delete(demo, 2, 1)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  3],
        [ 4,  5,  7],
        [ 8,  9, 11]]))

## 数组插入  
insert(arr，obj，values，axis)：依据索引在特定轴之前插入值。

In [30]:
demo1 = np.arange(12).reshape(3, 4)
demo2 = np.arange(4)
np.insert(demo1, 2, demo2, 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

## 附加  
append(arr，values，axis)：将值附加到数组的末尾，并返回 1 维数组。

In [31]:
demo1 = np.arange(6).reshape(2, 3)
demo2 = np.arange(3)
demo1, demo2, np.append(demo1, demo2)

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([0, 1, 2]),
 array([0, 1, 2, 3, 4, 5, 0, 1, 2]))

## 重设尺寸  
resize(a，new_shape)：对数组尺寸进行重新设定。  
  
*reshape 在改变形状时，不会影响原数组，相当于对原数组做了一份拷贝。而 resize 则是对原数组执行操作。*

In [32]:
demo = np.arange(10)
demo.resize(2, 5)
demo

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 翻转数组  
* fliplr(m)：左右翻转数组。  
* flipud(m)：上下翻转数组。

In [33]:
demo = np.arange(9).reshape(3, 3)
demo, np.fliplr(demo), np.flipud(demo)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[2, 1, 0],
        [5, 4, 3],
        [8, 7, 6]]),
 array([[6, 7, 8],
        [3, 4, 5],
        [0, 1, 2]]))

## NumPy 随机数  
numpy.random.rand(d0, d1, ..., dn)：指定一个数组，并使用 [0, 1) 区间随机数据填充，这些数据均匀分布。

In [34]:
np.random.rand(2, 5)

array([[0.6513672 , 0.52781785, 0.10791755, 0.1321566 , 0.26838457],
       [0.99358208, 0.46343937, 0.95349303, 0.89577157, 0.46440936]])

numpy.random.randn(d0, d1, ..., dn)：从标准正态分布中返回一个或多个样本值。

In [35]:
np.random.randn(1, 10)

array([[ 0.31139024,  0.50258523, -0.11697193,  2.50574865, -1.17740451,
        -0.40342896, -0.84467368,  1.42308693, -1.0190145 , -2.0750146 ]])

randint(low, high, size, dtype)：生成 [low, high) 的随机整数。

In [36]:
np.random.randint(2, 5, 10)

array([2, 4, 3, 3, 4, 3, 2, 2, 2, 4])

random_sample(size)：在 [0, 1) 区间内生成指定 size 的随机浮点数。  
  
与 numpy.random.random_sample 类似的方法还有：  
* numpy.random.random(\[size])  
* numpy.random.ranf(\[size])  
* numpy.random.sample(\[size])

In [37]:
np.random.random_sample([10])

array([0.44728317, 0.27198233, 0.77374847, 0.89848908, 0.05425053,
       0.34931227, 0.96390144, 0.47219885, 0.89241342, 0.41473583])

choice(a, size, replace, p)：在给定的数组里随机抽取几个值，该方法类似于随机抽样。

In [38]:
np.random.choice(10, 5)

array([8, 3, 1, 8, 7])

## 概率密度分布  
* numpy.random.beta(a，b，size)：从 Beta 分布中生成随机数。  
* numpy.random.binomial(n, p, size)：从二项分布中生成随机数。  
* numpy.random.chisquare(df，size)：从卡方分布中生成随机数。  
* numpy.random.dirichlet(alpha，size)：从 Dirichlet 分布中生成随机数。  
* numpy.random.exponential(scale，size)：从指数分布中生成随机数。  
* numpy.random.f(dfnum，dfden，size)：从 F 分布中生成随机数。  
* numpy.random.gamma(shape，scale，size)：从 Gamma 分布中生成随机数。  
* numpy.random.geometric(p，size)：从几何分布中生成随机数。  
* numpy.random.gumbel(loc，scale，size)：从 Gumbel 分布中生成随机数。  
* numpy.random.hypergeometric(ngood, nbad, nsample, size)：从超几何分布中生成随机数。  
* numpy.random.laplace(loc，scale，size)：从拉普拉斯双指数分布中生成随机数。  
* numpy.random.logistic(loc，scale，size)：从逻辑分布中生成随机数。  
* numpy.random.lognormal(mean，sigma，size)：从对数正态分布中生成随机数。  
* numpy.random.logseries(p，size)：从对数系列分布中生成随机数。  
* numpy.random.multinomial(n，pvals，size)：从多项分布中生成随机数。  
* numpy.random.multivariate_normal(mean, cov, size)：从多变量正态分布绘制随机样本。  
* numpy.random.negative_binomial(n, p, size)：从负二项分布中生成随机数。  
* numpy.random.noncentral_chisquare(df，nonc，size)：从非中心卡方分布中生成随机数。  
* numpy.random.noncentral_f(dfnum, dfden, nonc, size)：从非中心 F 分布中抽取样本。  
* numpy.random.normal(loc，scale，size)：从正态分布绘制随机样本。  
* numpy.random.pareto(a，size)：从具有指定形状的 Pareto II 或 Lomax 分布中生成随机数。  
* numpy.random.poisson(lam，size)：从泊松分布中生成随机数。  
* numpy.random.power(a，size)：从具有正指数 a-1 的功率分布中在 0，1 中生成随机数。  
* numpy.random.rayleigh(scale，size)：从瑞利分布中生成随机数。  
* numpy.random.standard_cauchy(size)：从标准 Cauchy 分布中生成随机数。  
* numpy.random.standard_exponential(size)：从标准指数分布中生成随机数。  
* numpy.random.standard_gamma(shape，size)：从标准 Gamma 分布中生成随机数。  
* numpy.random.standard_normal(size)：从标准正态分布中生成随机数。  
* numpy.random.standard_t(df，size)：从具有 df 自由度的标准学生 t 分布中生成随机数。  
* numpy.random.triangular(left，mode，right，size)：从三角分布中生成随机数。  
* numpy.random.uniform(low，high，size)：从均匀分布中生成随机数。  
* numpy.random.vonmises(mu，kappa，size)：从 von Mises 分布中生成随机数。  
* numpy.random.wald(mean，scale，size)：从 Wald 或反高斯分布中生成随机数。  
* numpy.random.weibull(a，size)：从威布尔分布中生成随机数。  
* numpy.random.zipf(a，size)：从 Zipf 分布中生成随机数。

# 数学函数  
## 三角函数  
* numpy.sin(x)：三角正弦。  
* numpy.cos(x)：三角余弦。  
* numpy.tan(x)：三角正切。  
* numpy.arcsin(x)：三角反正弦。  
* numpy.arccos(x)：三角反余弦。  
* numpy.arctan(x)：三角反正切。  
* numpy.hypot(x1,x2)：直角三角形求斜边。  
* numpy.degrees(x)：弧度转换为度。  
* numpy.radians(x)：度转换为弧度。  
* numpy.deg2rad(x)：度转换为弧度。  
* numpy.rad2deg(x)：弧度转换为度。

In [39]:
np.rad2deg(np.pi), np.deg2rad(180)

(180.0, 3.141592653589793)

## 双曲函数  
* numpy.sinh(x)：双曲正弦。  
* numpy.cosh(x)：双曲余弦。  
* numpy.tanh(x)：双曲正切。  
* numpy.arcsinh(x)：反双曲正弦。  
* numpy.arccosh(x)：反双曲余弦。  
* numpy.arctanh(x)：反双曲正切。  
## 数值修约  
* numpy.around(a)：平均到给定的小数位数。  
* numpy.round_(a)：将数组舍入到给定的小数位数。  
* numpy.rint(x)：修约到最接近的整数。  
* numpy.fix(x, y)：向 0 舍入到最接近的整数。  
* numpy.floor(x)：返回输入的底部(标量 x 的底部是最大的整数 i)。  
* numpy.ceil(x)：返回输入的上限(标量 x 的底部是最小的整数 i)。  
* numpy.trunc(x)：返回输入的截断值。

In [40]:
demo = np.random.rand(3)
demo, np.rint(demo)

(array([0.8474565 , 0.43852818, 0.26383249]), array([1., 0., 0.]))

## 求和、求积、差分  
* numpy.prod(a, axis, dtype, keepdims)：返回指定轴上的数组元素的乘积。  
* numpy.sum(a, axis, dtype, keepdims)：返回指定轴上的数组元素的总和。  
* numpy.nanprod(a, axis, dtype, keepdims)：返回指定轴上的数组元素的乘积, 将 NaN 视作 1。  
* numpy.nansum(a, axis, dtype, keepdims)：返回指定轴上的数组元素的总和, 将 NaN 视作 0。  
* numpy.cumprod(a, axis, dtype)：返回沿给定轴的元素的累积乘积。  
* numpy.cumsum(a, axis, dtype)：返回沿给定轴的元素的累积总和。  
* numpy.nancumprod(a, axis, dtype)：返回沿给定轴的元素的累积乘积, 将 NaN 视作 1。  
* numpy.nancumsum(a, axis, dtype)：返回沿给定轴的元素的累积总和, 将 NaN 视作 0。  
* numpy.diff(a, n, axis)：计算沿指定轴的第 n 个离散差分。  
* numpy.ediff1d(ary, to_end, to_begin)：数组的连续元素之间的差异。  
* numpy.gradient(f)：返回 N 维数组的梯度。  
* numpy.cross(a, b, axisa, axisb, axisc, axis)：返回两个(数组）向量的叉积。  
* numpy.trapz(y, x, dx, axis)：使用复合梯形规则沿给定轴积分。

In [41]:
demo = np.arange(10)
demo, np.sum(demo)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 45)

## 指数和对数  
* numpy.exp(x)：计算输入数组中所有元素的指数。  
* numpy.log(x)：计算自然对数。  
* numpy.log10(x)：计算常用对数。  
* numpy.log2(x)：计算二进制对数。  
## 算术运算  
* numpy.add(x1, x2)：对应元素相加。  
* numpy.reciprocal(x)：求倒数 1/x。  
* numpy.negative(x)：求对应负数。  
* numpy.multiply(x1, x2)：求解乘法。  
* numpy.divide(x1, x2)：相除 x1/x2。  
* numpy.power(x1, x2)：类似于 x1^x2。  
* numpy.subtract(x1, x2)：减法。  
* numpy.fmod(x1, x2)：返回除法的元素余项。  
* numpy.mod(x1, x2)：返回余项。  
* numpy.modf(x1)：返回数组的小数和整数部分。  
* numpy.remainder(x1, x2)：返回除法余数。  
## 矩阵和向量积  
* numpy.dot(a, b)：求解两个数组的点积。  
* numpy.vdot(a, b)：求解两个向量的点积。  
* numpy.inner(a, b)：求解两个数组的内积。  
* numpy.outer(a, b)：求解两个向量的外积。  
* numpy.matmul(a, b)：求解两个数组的矩阵乘积。  
* numpy.tensordot(a, b)：求解张量点积。  
* numpy.kron(a, b)：计算 Kronecker 乘积。  
## 其他类别  
* numpy.angle(z, deg)：返回复参数的角度。  
* numpy.real(val)：返回数组元素的实部。  
* numpy.imag(val)：返回数组元素的虚部。  
* numpy.conj(x)：按元素方式返回共轭复数。  
* numpy.convolve(a, v, mode)：返回线性卷积。  
* numpy.sqrt(x)：平方根。  
* numpy.cbrt(x)：立方根。  
* numpy.square(x)：平方。  
* numpy.absolute(x)：绝对值, 可求解复数。  
* numpy.fabs(x)：绝对值。  
* numpy.sign(x)：符号函数。  
* numpy.maximum(x1, x2)：最大值。  
* numpy.minimum(x1, x2)：最小值。  
* numpy.nan_to_num(x)：用 0 替换 NaN。  
* numpy.interp(x, xp, fp, left, right, period)：线性插值。  
## 代数运算  
* numpy.linalg.cholesky(a)：Cholesky 分解。  
* numpy.linalg.qr(a ,mode)：计算矩阵的 QR 因式分解。  
* numpy.linalg.svd(a ,full_matrices,compute_uv)：奇异值分解。  
* numpy.linalg.eig(a)：计算正方形数组的特征值和右特征向量。  
* numpy.linalg.eigh(a, UPLO)：返回 Hermitian 或对称矩阵的特征值和特征向量。  
* numpy.linalg.eigvals(a)：计算矩阵的特征值。  
* numpy.linalg.eigvalsh(a, UPLO)：计算 Hermitian 或真实对称矩阵的特征值。  
* numpy.linalg.norm(x ,ord,axis,keepdims)：计算矩阵或向量范数。  
* numpy.linalg.cond(x ,p)：计算矩阵的条件数。  
* numpy.linalg.det(a)：计算数组的行列式。  
* numpy.linalg.matrix_rank(M ,tol)：使用奇异值分解方法返回秩。  
* numpy.linalg.slogdet(a)：计算数组的行列式的符号和自然对数。  
* numpy.trace(a ,offset,axis1,axis2,dtype,out)：沿数组的对角线返回总和。  
* numpy.linalg.solve(a, b)：求解线性矩阵方程或线性标量方程组。  
* numpy.linalg.tensorsolve(a, b ,axes)：为 x 解出张量方程 a x = b  
* numpy.linalg.lstsq(a, b ,rcond)：将最小二乘解返回到线性矩阵方程。  
* numpy.linalg.inv(a)：计算逆矩阵。  
* numpy.linalg.pinv(a ,rcond)：计算矩阵的（Moore-Penrose）伪逆。  
* numpy.linalg.tensorinv(a ,ind)：计算 N 维数组的逆。  
# 数组索引和切片  
## 数组索引  
### 一维数组

In [42]:
demo = np.arange(10)
demo, demo[1], demo[[1, 2, 3]]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 1, array([1, 2, 3]))

### 二维数组

In [43]:
demo = np.arange(20).reshape(4, 5)
demo, demo[1], demo[1, 2], demo[[1, 3], [1, 3]]

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([5, 6, 7, 8, 9]),
 7,
 array([ 6, 18]))

需要注意索引的对应关系，实际获取的是 \[1, 1]，也就是第 2 行和第 2 列对于的值 6。以及 \[3, 3]，也就是第 4 行和第 4 列对应的值 18。
### 三维数组

In [44]:
demo = np.arange(30).reshape(2, 5, 3)
demo, demo[1], demo[1, 1], demo[1, 1, 1], demo[[0, 1], [1, 3], [1, 1]]

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],
 
        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]]),
 array([[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]),
 array([18, 19, 20]),
 19,
 array([ 4, 25]))

## 数组切片  
NumPy 里面针对Ndarray的数组切片和 Python 里的list 切片操作是一样的。其语法为：  
Ndarray\[start:stop:step]  
  
### 一维数组

In [45]:
demo = np.arange(10)
demo, demo[:5], demo[5:], demo[::2]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([0, 2, 4, 6, 8]))

### 多维数组  
对于多维数组，只需要用逗号，分割不同维度即可

In [46]:
demo = np.arange(20).reshape(4, 5)
demo, demo[1:3, 1:4], demo[1:3, ::2]

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[ 6,  7,  8],
        [11, 12, 13]]),
 array([[ 5,  7,  9],
        [10, 12, 14]]))

In [47]:
demo = np.arange(30).reshape(2, 5, 3)
demo, demo[1:, 1:4, 1:]

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],
 
        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]]),
 array([[[19, 20],
         [22, 23],
         [25, 26]]]))

## 排序、搜索、计数  
* argmax(a ,axis,out)：返回数组中指定轴的最大值的索引。  
* nanargmax(a ,axis)：返回数组中指定轴的最大值的索引,忽略 NaN。  
* argmin(a ,axis,out)：返回数组中指定轴的最小值的索引。  
* nanargmin(a ,axis)：返回数组中指定轴的最小值的索引,忽略 NaN。  
* argwhere(a)：返回数组中非 0 元素的索引,按元素分组。  
* nonzero(a)：返回数组中非 0 元素的索引。  
* flatnonzero(a)：返回数组中非 0 元素的索引,并铺平。  
* where(条件,x,y)：根据指定条件,从指定行、列返回元素。  
* searchsorted(a,v ,side,sorter)：查找要插入元素以维持顺序的索引。  
* extract(condition,arr)：返回满足某些条件的数组的元素。  
* count_nonzero(a)：计算数组中非 0 元素的数量。